# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministro',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suministro',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suministro',
            name='referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suministro',
            name='unidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
