# Generated by Django 2.0 on 2017-12-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0003_suministro_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suministro',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='suministro',
            name='comentario',
        ),
    ]
