# Generated by Django 2.0 on 2017-12-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0004_auto_20171218_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministro',
            name='codigo_lpu',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='suministro',
            name='codigo_mm',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='suministro',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suministro',
            name='descripcion_lpu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suministro',
            name='valor_lpu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
