# Generated by Django 2.0 on 2018-03-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsistemas', '0002_remove_subsistema_estacion'),
        ('suministros', '0007_auto_20171221_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministro',
            name='codigo_mm',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='suministro',
            unique_together={('subsistema', 'codigo_mm')},
        ),
    ]
