# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estaciones', '0012_auto_20171127_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_oferta', models.CharField(blank=True, max_length=255, null=True)),
                ('tarea', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_tarea', models.CharField(blank=True, max_length=255, null=True)),
                ('tas_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('encargado_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_lpu', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_mm', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_sap', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_oferta', models.CharField(blank=True, max_length=255, null=True)),
                ('subestado_oferta', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='estaciones.Estacion')),
            ],
            options={
                'verbose_name': 'oferta',
                'verbose_name_plural': 'ofertas',
                'ordering': ('creado',),
            },
        ),
    ]
