# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subsistemas', '0001_initial'),
        ('ofertas', '0002_oferta_servicio'),
        ('suministros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='subsistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='subsistemas.Subsistema'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='suministros.Suministro'),
        ),
    ]
