# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_auto_20171129_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='codigo_lpu',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='codigo_mm',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='codigo_sap',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='descripcion_tarea',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='encargado_cliente',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='estacion',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='subsistema',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='suministro',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='tarea',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='tas_cliente',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='tipo_oferta',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='unidad',
        ),
    ]
