# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_subsistema'),
        ('suministros', '0001_initial'),
        ('ofertas', '0005_oferta_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='servicios.Servicio'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='suministros.Suministro'),
        ),
    ]
