# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0006_auto_20171202_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='tipo_oferta',
            field=models.CharField(blank=True, choices=[('SMU', 'ASMU'), ('BackLog', 'BackLog'), ('Hurto', 'Hurto')], max_length=255, null=True),
        ),
    ]
