# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0007_oferta_tipo_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='tipo_oferta',
            field=models.CharField(blank=True, choices=[('SMU', 'SMU'), ('BackLog', 'BackLog'), ('Hurto', 'Hurto')], max_length=255, null=True),
        ),
    ]
