# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0008_auto_20171208_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='descripcion_tarea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='encargado_cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tarea',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='usuario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
