# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0009_auto_20171209_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
