# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 01:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0010_oferta_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='comentario_acta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='comentario_almacenista',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='comentario_analista',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='comentario_coordinador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='comentario_facturador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='comentario_supervisor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='confirmacion_recibido',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO'), ('PENDIENTE', 'PENDIENTE')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_conciliado_cliente',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_despacho_compras',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_despacho_supervisor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_ejecucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_entrga_almacen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_envio_acta_smu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_envio_cliente',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_firma_acta_smu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_gr_smu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_po',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_recibido_cliente',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_respuesta_cliente',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_respuesta_compras',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='margen',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='oferta',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('LPU', 'LPU'), ('APU', 'APU'), ('FEE', 'FEE')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='numero_oferta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='percio_total_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='percio_total_proveedor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='percio_total_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='percio_unidad_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='percio_unidad_proveedor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='percio_unidad_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='spo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo_adquisicion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo_respuesta_cliente',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO'), ('APROBADO MENOR VALOR', 'APROBADO MENOR VALOR'), ('SIN RESPUESTA', 'SIN RESPUESTA')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='valor_conciliado_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='estado_oferta',
            field=models.CharField(blank=True, choices=[('PENDIENTE EJECUCION', 'PENDIENTE EJECUCION')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='subestado_oferta',
            field=models.CharField(blank=True, choices=[('PENDIENTE PO', 'PENDIENTE PO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_oferta',
            field=models.CharField(blank=True, choices=[('SMU', 'SMU'), ('BACKLOG', 'BACKLOG'), ('HURTO', 'HURTO')], max_length=255, null=True),
        ),
    ]
