# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0011_auto_20171210_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='spo',
            new_name='po',
        ),
    ]
