# Generated by Django 2.0 on 2017-12-15 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0012_auto_20171211_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='fecha_entrga_almacen',
            new_name='fecha_entrega_almacen',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='percio_total_cliente',
            new_name='precio_total_cliente',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='percio_total_proveedor',
            new_name='precio_total_proveedor',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='percio_total_venta',
            new_name='precio_total_venta',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='percio_unidad_cliente',
            new_name='precio_unidad_cliente',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='percio_unidad_proveedor',
            new_name='precio_unidad_proveedor',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='percio_unidad_venta',
            new_name='precio_unidad_venta',
        ),
    ]
