# Generated by Django 2.0 on 2017-12-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0013_auto_20171214_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
