# Generated by Django 2.0 on 2017-12-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
        ('ofertas', '0014_oferta_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='suministro',
        ),
        migrations.AddField(
            model_name='oferta',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='ordenes.Orden'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='estado_oferta',
            field=models.CharField(blank=True, choices=[('PENDIENTE EJECUCION', 'PENDIENTE EJECUCION'), ('PENDIENTE COTIZACION PROVEEDOR', 'PENDIENTE COTIZACION PROVEEDOR'), ('PENDIENTE PO', 'PENDIENTE PO'), ('SIN PROCESAR', 'SIN PROCESAR'), ('SOLICITUD CANCELADA', 'SOLICITUD CANCELADA'), ('PENDIENTE APROBACION CLARO', 'PENDIENTE APROBACION CLARO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='subestado_oferta',
            field=models.CharField(blank=True, choices=[('PENDIENTE PO', 'PENDIENTE PO'), ('PENDIENTE APROBACION COMPRAS CLARO', 'PENDIENTE APROBACION COMPRAS CLARO'), ('PENDIENTE APROBACION ZONA CLARO', 'PENDIENTE APROBACION ZONA CLARO'), ('PENDIENTE EJECUCION', 'PENDIENTE EJECUCION'), ('SOLICITUD CANCELADA', 'SOLICITUD CANCELADA'), ('SUMINISTRO EN IMPORTACION', 'SUMINISTRO EN IMPORTACION'), ('NO APROBADO POR COMPRAS NOKIA POR MENOR VALOR', 'NO APROBADO POR COMPRAS NOKIA POR MENOR VALOR'), ('RECIBIDO DE SUPERVISOR', 'RECIBIDO DE SUPERVISOR'), ('EN REVISION ANALISTA OFERTAS NOKIA', 'EN REVISION ANALISTA OFERTAS NOKIA'), ('EN PROCESO DE COTIZACION PROVEEDORES', 'EN PROCESO DE COTIZACION PROVEEDORES')], max_length=255, null=True),
        ),
    ]
