# Generated by Django 2.0 on 2017-12-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0015_auto_20171218_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='orden',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenes.Orden'),
        ),
    ]
