# Generated by Django 2.0 on 2017-12-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0016_auto_20171219_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='orden',
            new_name='orden_suministro',
        ),
    ]
