# Generated by Django 2.0 on 2017-12-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_ordenservicio'),
        ('ofertas', '0017_auto_20171219_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='orden_servicio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenes.OrdenServicio'),
        ),
    ]
