# Generated by Django 2.0 on 2017-12-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0018_oferta_orden_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='fecha_envio_cliente',
            new_name='fecha_envio_oferta_cliente',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='fecha_recibido_cliente',
            new_name='fecha_envio_oferta_cliente_negociada',
        ),
        migrations.AddField(
            model_name='oferta',
            name='descripcion_ods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_recibido_ods',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_respuesta_cliente_negociada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='naturaleza_servicio',
            field=models.CharField(blank=True, choices=[('PREVENTIVO', 'PREVENTIVO'), ('CORRECTIVO', 'CORRECTIVO'), ('EMERGENCIA', 'EMERGENCIA'), ('INTEGRAL', 'INTEGRAL'), ('PREDICTIVO', 'PREDICTIVO')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='proveedor',
            field=models.CharField(blank=True, choices=[('CUMMINS DE LOS ANDES', 'CUMMINS DE LOS ANDES'), ('METRICOM', 'METRICOM'), ('BIOTECNICA', 'BIOTECNICA'), ('CASA INGLESA', 'CASA INGLESA'), ('CONECTAR', 'CONECTAR'), ('DECOM', 'DECOM'), ('ELECTRICOS SURAMERICA', 'ELECTRICOS SURAMERICA'), ('ELTEK', 'ELTEK'), ('FERNEY GUTIERREZ', 'FERNEY GUTIERREZ'), ('INGYTELCOM', 'INGYTELCOM'), ('MICROLINK', 'MICROLINK'), ('NESITELCO', 'NESITELCO'), ('OSC', 'OSC'), ('MSI', 'MSI'), ('PRODATEL', 'PRODATEL'), ('SELLING', 'SELLING'), ('SUSEQUID', 'SUSEQUID'), ('TRS', 'TRS'), ('UNION ELECTRICA', 'UNION ELECTRICA'), ('CAJOS', 'CAJOS')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='semana_despacho_compras',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='semana_despacho_supervisor',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='semana_envio_oferta_cliente',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='semana_envio_oferta_cliente_negociada',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='semana_recibido_ods',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='semana_respuesta_cliente',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='semana_respuesta_cliente_negociada',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='semana_respuesta_compras',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tas_oferta_anterior',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo_acceso',
            field=models.CharField(blank=True, choices=[('URBANO ', 'URBANO'), ('RURAL', 'RURAL'), ('ACCESO DIFICIL', 'ACCESO DIFICIL'), ('FLUVIAL', 'FLUVIAL'), ('AEREO', 'AEREO'), ('COMUNIDAD INDIGENA', 'COMUNIDAD INDIGENA')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo_elemento',
            field=models.CharField(blank=True, choices=[('CAPEX', 'CAPEX'), ('OPEX', 'OPEX')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo_respuesta_cliente_negociada',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO'), ('APROBADO MENOR VALOR', 'APROBADO MENOR VALOR'), ('SIN RESPUESTA', 'SIN RESPUESTA')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_adquisicion',
            field=models.CharField(blank=True, choices=[('PROVEEDOR', 'PROVEEDOR'), ('PERSONAL NOKIA', 'PERSONAL NOKIA'), ('BODEGA', 'BODEGA'), ('COMPRA LOCAL', 'COMPRA LOCAL'), ('INTERMEDIARIO', 'INTERMEDIARIO'), ('PALABRERO', 'PALABRERO')], max_length=255, null=True),
        ),
    ]
