# Generated by Django 2.0 on 2017-12-20 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0019_auto_20171219_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='margen',
            field=models.IntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='precio_total_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='precio_total_proveedor',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='precio_total_venta',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
