# Generated by Django 2.0 on 2018-01-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0021_auto_20171220_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='tarea',
            new_name='work_order',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo_sitio',
            field=models.CharField(blank=True, choices=[('URBANO', 'URBANO'), ('RURAL', 'RURAL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='estado_oferta',
            field=models.CharField(blank=True, choices=[('PENDIENTE COTIZACION PROVEEDOR', 'PENDIENTE COTIZACION PROVEEDOR'), ('PENDIENTE APROBACION COMPRAS CLARO', 'PENDIENTE APROBACION COMPRAS CLARO'), ('PENDIENTE EJECUCION CAMPO', 'PENDIENTE EJECUCION CAMPO'), ('PENDIENTE ENTREGA PROVEEDOR', 'PENDIENTE ENTREGA PROVEEDOR'), ('PENDIENTE PO', 'PENDIENTE PO'), ('SIN PROCESAR ANALISTA', 'SIN PROCESAR ANALISTA'), ('SOLICITUD APROBADA CLARO', 'SOLICITUD APROBADA CLARO'), ('SOLICITUD APROBADA NOKIA MENOR VALOR', 'SOLICITUD APROBADA NOKIA MENOR VALOR'), ('SOLICITUD CANCELADA COMPRAS CLARO', 'SOLICITUD CANCELADA COMPRAS CLARO'), ('SOLICITUD CANCELADA NOKIA POR MENOR VALOR', 'SOLICITUD CANCELADA NOKIA POR MENOR VALOR'), ('PENDIENTE APROBACION ZONA CLARO', 'PENDIENTE APROBACION ZONA CLARO'), ('EJECUTADO NOKIA', 'EJECUTADO NOKIA'), ('EJECUTADO CLARO', 'EJECUTADO CLARO'), ('SOLICITUD CANCELADA ZONA CLARO', 'SOLICITUD CANCELADA ZONA CLARO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_despacho_supervisor',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='proveedor',
            field=models.CharField(blank=True, choices=[('CUMMINS DE LOS ANDES', 'CUMMINS DE LOS ANDES'), ('METRICOM', 'METRICOM'), ('BIOTECNICA', 'BIOTECNICA'), ('CASA INGLESA', 'CASA INGLESA'), ('CONECTAR', 'CONECTAR'), ('DECOM', 'DECOM'), ('ELECTRICOS SURAMERICA', 'ELECTRICOS SURAMERICA'), ('ELTEK', 'ELTEK'), ('FERNEY GUTIERREZ', 'FERNEY GUTIERREZ'), ('INGYTELCOM', 'INGYTELCOM'), ('MICROLINK', 'MICROLINK'), ('NESITELCO', 'NESITELCO'), ('OSC', 'OSC'), ('MSI', 'MSI'), ('PRODATEL', 'PRODATEL'), ('SELLING', 'SELLING'), ('SUSEQUID', 'SUSEQUID'), ('TRS', 'TRS'), ('UNION ELECTRICA', 'UNION ELECTRICA'), ('CAJOS', 'CAJOS'), ('NOKIA', 'NOKIA'), ('CLARO', 'CLARO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='subestado_oferta',
            field=models.CharField(blank=True, choices=[('EN PROCESO DE COTIZACION PROVEEDORES', 'EN PROCESO DE COTIZACION PROVEEDORES'), ('PENDIENTE APROBACION COMPRAS CLARO', 'PENDIENTE APROBACION COMPRAS CLARO'), ('APROBADO CLARO', 'APROBADO CLARO'), ('PENDIENTE ENTREGA PROVEEDOR', 'PENDIENTE ENTREGA PROVEEDOR'), ('NO APROBADO POR COMPRAS NOKIA POR MENOR VALOR', 'NO APROBADO POR COMPRAS NOKIA POR MENOR VALOR'), ('PENDIENTE APROBACION ZONA CLARO', 'PENDIENTE APROBACION ZONA CLARO'), ('PENDIENTE EJECUCION', 'PENDIENTE EJECUCION'), ('SOLICITUD CANCELADA COMPRAS', 'SOLICITUD CANCELADA COMPRAS'), ('SOLICITUD CANCELADA NOKIA POR MENOR VALOR', 'SOLICITUD CANCELADA NOKIA POR MENOR VALOR'), ('RECIBIDO DE SUPERVISOR', 'RECIBIDO DE SUPERVISOR'), ('PENDIENTE PO', 'PENDIENTE PO'), ('SUMINISTRO EN IMPORTACION', 'SUMINISTRO EN IMPORTACION'), ('EN REVISION ANALISTA OFERTAS NOKIA', 'EN REVISION ANALISTA OFERTAS NOKIA'), ('SIN PROCESAR ANALISTA', 'SIN PROCESAR ANALISTA'), ('EJECUTADO NOKIA', 'EJECUTADO NOKIA'), ('EJECUTADO CLARO', 'EJECUTADO CLARO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_acceso',
            field=models.CharField(blank=True, choices=[('ACCESO DIFICIL', 'ACCESO DIFICIL'), ('FLUVIAL', 'FLUVIAL'), ('AEREO', 'AEREO'), ('COMUNIDAD INDIGENA', 'COMUNIDAD INDIGENA'), ('PALABRERO', 'PALABRERO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_adquisicion',
            field=models.CharField(blank=True, choices=[('PROVEEDOR', 'PROVEEDOR'), ('PERSONAL NOKIA', 'PERSONAL NOKIA'), ('BODEGA', 'BODEGA'), ('COMPRA LOCAL', 'COMPRA LOCAL'), ('INTERMEDIARIO', 'INTERMEDIARIO'), ('PALABRERO', 'PALABRERO'), ('SUMINISTRADO CLIENTE', 'SUMINISTRADO CLIENTE')], max_length=255, null=True),
        ),
    ]
