# Generated by Django 2.0 on 2018-01-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0022_auto_20180117_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='valor_po',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
