# Generated by Django 2.0 on 2018-01-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0023_oferta_valor_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='numero_oferta',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tas_oferta_anterior',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='work_order',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
