# Generated by Django 2.0 on 2018-01-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0024_auto_20180119_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='tipo_acceso',
            field=models.CharField(blank=True, choices=[('URBANO', 'URBANO'), ('ACCESO DIFICIL', 'ACCESO DIFICIL'), ('FLUVIAL', 'FLUVIAL'), ('AEREO', 'AEREO'), ('COMUNIDAD INDIGENA', 'COMUNIDAD INDIGENA'), ('PALABRERO', 'PALABRERO')], max_length=255, null=True),
        ),
    ]
