# Generated by Django 2.0 on 2018-01-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0025_auto_20180121_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='id_solicitud',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
