# Generated by Django 2.0 on 2018-03-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0026_oferta_id_solicitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'ordering': ('-creado',), 'verbose_name': 'oferta', 'verbose_name_plural': 'ofertas'},
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_respuesta_cliente',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO'), ('APROBADO MENOR VALOR', 'APROBADO MENOR VALOR'), ('SIN RESPUESTA', 'SIN RESPUESTA'), ('N/A', 'N/A')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_respuesta_cliente_negociada',
            field=models.CharField(blank=True, choices=[('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO'), ('APROBADO MENOR VALOR', 'APROBADO MENOR VALOR'), ('SIN RESPUESTA', 'SIN RESPUESTA'), ('N/A', 'N/A')], max_length=255, null=True),
        ),
    ]
