# Generated by Django 2.0 on 2018-05-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0027_auto_20180309_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='proveedor',
            field=models.CharField(blank=True, choices=[('CUMMINS DE LOS ANDES', 'CUMMINS DE LOS ANDES'), ('METRICOM', 'METRICOM'), ('BIOTECNICA', 'BIOTECNICA'), ('CASA INGLESA', 'CASA INGLESA'), ('CONECTAR', 'CONECTAR'), ('DECOM', 'DECOM'), ('ELECTRICOS SURAMERICA', 'ELECTRICOS SURAMERICA'), ('ELTEK', 'ELTEK'), ('FERNEY GUTIERREZ', 'FERNEY GUTIERREZ'), ('INGYTELCOM', 'INGYTELCOM'), ('MICROLINK', 'MICROLINK'), ('NESITELCO', 'NESITELCO'), ('OSC', 'OSC'), ('MSI', 'MSI'), ('PRODATEL', 'PRODATEL'), ('SELLING', 'SELLING'), ('SUSEQUID', 'SUSEQUID'), ('TRS', 'TRS'), ('UNION ELECTRICA', 'UNION ELECTRICA'), ('CAJOS', 'CAJOS'), ('NOKIA', 'NOKIA'), ('CLARO', 'CLARO'), ('SUMA', 'SUMA'), ('N/A', 'N/A')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_acceso',
            field=models.CharField(blank=True, choices=[('URBANO', 'URBANO'), ('ACCESO DIFICIL', 'ACCESO DIFICIL'), ('FLUVIAL', 'FLUVIAL'), ('AEREO', 'AEREO'), ('COMUNIDAD INDIGENA', 'COMUNIDAD INDIGENA'), ('PALABRERO', 'PALABRERO'), ('RURAL 4X4', 'RURAL 4X4')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_adquisicion',
            field=models.CharField(blank=True, choices=[('PROVEEDOR', 'PROVEEDOR'), ('PERSONAL NOKIA', 'PERSONAL NOKIA'), ('BODEGA NOKIA', 'BODEGA NOKIA'), ('BODEGA CLARO', 'BODEGA CLARO'), ('COMPRA LOCAL', 'COMPRA LOCAL'), ('INTERMEDIARIO', 'INTERMEDIARIO'), ('PALABRERO', 'PALABRERO'), ('SUMINISTRADO CLIENTE', 'SUMINISTRADO CLIENTE'), ('N/A', 'N/A')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_elemento',
            field=models.CharField(blank=True, choices=[('CAPEX', 'CAPEX'), ('OPEX', 'OPEX'), ('N/A', 'N/A')], max_length=255, null=True),
        ),
    ]
