# Generated by Django 2.0 on 2017-12-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20171209_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
