# Generated by Django 2.0 on 2017-12-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_servicio_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='comentario',
        ),
    ]
