# Generated by Django 2.0 on 2017-12-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_20171218_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='marca',
            new_name='distancia',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='referencia',
            new_name='peso',
        ),
        migrations.AddField(
            model_name='servicio',
            name='codigo_lpu',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion_lpu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tiempo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='valor_lpu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
