# Generated by Django 2.0 on 2018-03-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsistemas', '0002_remove_subsistema_estacion'),
        ('servicios', '0007_auto_20171221_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='codigo_lpu',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='servicio',
            unique_together={('subsistema', 'codigo_lpu')},
        ),
    ]
