# Generated by Django 2.0 on 2018-03-16 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_auto_20180316_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='subsistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='subsistemas.Subsistema'),
        ),
    ]
