# Generated by Django 2.0 on 2018-05-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_auto_20180316_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='codigo_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
