# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('ubicacion_tecnica', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('estructura', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('categoria', models.CharField(max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'estacion',
                'verbose_name_plural': 'estaciones',
                'ordering': ('creado',),
            },
        ),
    ]
