# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacion',
            old_name='latitude',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='estacion',
            old_name='longitude',
            new_name='longitud',
        ),
    ]
