# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0002_auto_20171127_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacion',
            old_name='ubicacion_tecnica',
            new_name='ubicacion',
        ),
    ]
