# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0003_auto_20171127_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='estado',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='subestado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
