# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0008_auto_20171127_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='latitud',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='longitud',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
