# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0009_auto_20171127_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
