# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estaciones', '0012_auto_20171127_1840'),
        ('servicios', '0002_servicio_subsistema'),
        ('suministros', '0001_initial'),
        ('subsistemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('analista', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_oferta', models.CharField(blank=True, max_length=255, null=True)),
                ('tarea', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_tarea', models.CharField(blank=True, max_length=255, null=True)),
                ('tas_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('encargado_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_lpu', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_mm', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_sap', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_solicitud', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='estaciones.Estacion')),
                ('servicio', models.ManyToManyField(blank=True, related_name='solicitudes', to='servicios.Servicio')),
                ('subsistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='subsistemas.Subsistema')),
                ('suministro', models.ManyToManyField(blank=True, related_name='solicitudes', to='suministros.Suministro')),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
                'ordering': ('creado',),
            },
        ),
    ]
