# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_auto_20171202_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='suministros',
            field=models.ManyToManyField(blank=True, related_name='solicitudes', to='suministros.Suministro'),
        ),
    ]
