# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_auto_20171202_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='cantidad',
            new_name='tas',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='codigo_lpu',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='codigo_mm',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='codigo_sap',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='descripcion_tarea',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='encargado_cliente',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='tarea',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='tas_cliente',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='tipo_oferta',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.BooleanField(default=False),
        ),
    ]
