# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_solicitud_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='analista_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='supervisor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
