# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_auto_20171208_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('ALTA', 'Alta'), ('MEDIA', 'MEDIA'), ('BAJA', 'BAJA')], max_length=255, null=True),
        ),
    ]
