# Generated by Django 2.0 on 2017-12-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_auto_20171211_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='suministros',
        ),
    ]
