# Generated by Django 2.0 on 2018-01-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_auto_20171218_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='tas',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
