# Generated by Django 2.0 on 2018-03-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_auto_20180119_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ('-creado',), 'verbose_name': 'solicitud', 'verbose_name_plural': 'solicitudes'},
        ),
    ]
