''' TIPO_OFERTA_CHOICES '''
SMU = 'SMU'
BACKLOG = 'BACKLOG'
HURTO = 'HURTO'
TIPO_OFERTA_CHOICES = (
    (SMU, 'SMU'),
    (BACKLOG, 'BACKLOG'),
    (HURTO, 'HURTO'),
)

''' MODALIDAD_CHOICES '''
LPU = 'LPU'
APU = 'APU'
FEE = 'FEE'
MODALIDAD_CHOICES = (
    (LPU, 'LPU'),
    (APU, 'APU'),
    (FEE, 'FEE'),
)

''' TIPO_RESPUESTA_CLIENTE_CHOICES '''
APROBADO = 'APROBADO'
RECHAZADO = 'RECHAZADO'
APROBADOMENORVALOR = 'APROBADO MENOR VALOR'
SINRESPUESTA = 'SIN RESPUESTA'
TIPO_RESPUESTA_CLIENTE_CHOICES = (
    (APROBADO, 'APROBADO'),
    (RECHAZADO, 'RECHAZADO'),
    (APROBADOMENORVALOR, 'APROBADO MENOR VALOR'),
    (SINRESPUESTA, 'SIN RESPUESTA'),
)

''' CONFIRMACION_RECIBIDO_CHOICES '''
SI = 'SI'
NO = 'NO'
PENDIENTE = 'PENDIENTE'
CONFIRMACION_RECIBIDO_CHOICES = (
    (SI, 'SI'),
    (NO, 'NO'),
    (PENDIENTE, 'PENDIENTE'),
)

''' SUBESTADO_OFERTA_CHOICES '''
PENDIENTEPO = 'PENDIENTE PO'
SUBESTADO_OFERTA_CHOICES = (
    (PENDIENTEPO, 'PENDIENTE PO'),
)

''' ESTADO_OFERTA_CHOICES '''
PENDIENTEEJECUCION = 'PENDIENTE EJECUCION'
ESTADO_OFERTA_CHOICES = (
    (PENDIENTEEJECUCION, 'PENDIENTE EJECUCION'),
)
