# Generated by Django 2.0 on 2017-12-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ('creado',), 'verbose_name': 'orden', 'verbose_name_plural': 'ordenes'},
        ),
    ]
