# Generated by Django 2.0 on 2017-12-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_auto_20171218_1352'),
        ('suministros', '0004_auto_20171218_1352'),
        ('ofertas', '0017_auto_20171219_1321'),
        ('servicios', '0005_auto_20171218_1352'),
        ('ordenes', '0002_auto_20171219_1146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orden',
            new_name='OrdenSuministro',
        ),
    ]
