# Generated by Django 2.0 on 2017-12-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_auto_20171219_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordensuministro',
            options={'ordering': ('creado',), 'verbose_name': 'orden suministro', 'verbose_name_plural': 'orden suministros'},
        ),
        migrations.RemoveField(
            model_name='ordensuministro',
            name='servicio',
        ),
    ]
