# Generated by Django 2.0 on 2017-12-19 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_auto_20171219_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordensuministro',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orden_suministros', to='solicitudes.Solicitud'),
        ),
        migrations.AlterField(
            model_name='ordensuministro',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orden_suministros', to='suministros.Suministro'),
        ),
    ]
