# Generated by Django 2.0 on 2017-12-19 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_auto_20171218_1352'),
        ('servicios', '0005_auto_20171218_1352'),
        ('ordenes', '0005_auto_20171219_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orden_servicios', to='servicios.Servicio')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orden_servicios', to='solicitudes.Solicitud')),
            ],
            options={
                'verbose_name': 'orden servicio',
                'verbose_name_plural': 'orden servicios',
                'ordering': ('creado',),
            },
        ),
    ]
