# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_auto_20171206_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='credential',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
