# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_auto_20171207_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='credential',
            field=models.TextField(unique=True),
        ),
    ]
